local baseID <const> = 1
local fearBaseID <const> = baseID
local keepsakeBaseID <const> = fearBaseID + 2
local weaponBaseID <const> = keepsakeBaseID + 33
local toolBaseID <const> = weaponBaseID + 33
ITEM_MAPPING = {
	-- keepsakes
	[keepsakeBaseID + 1] = {SilverWheel},
	[keepsakeBaseID + 2] = {KnuckleBones},
	[keepsakeBaseID + 3] = {LuckierTooth},
	[keepsakeBaseID + 4] = {GhostOnion},
	[keepsakeBaseID + 5] = {EvilEye},
	[keepsakeBaseID + 6] = {EngravedPin},
	[keepsakeBaseID + 7] = {DiscordantBell},
	[keepsakeBaseID + 8] = {GoldPurse},
	[keepsakeBaseID + 9] = {MetallicDroplet},
	[keepsakeBaseID + 10] = {WhiteAntler},
	[keepsakeBaseID + 11] = {MoonBeam},
	[keepsakeBaseID + 12] = {CloudBangle},
	[keepsakeBaseID + 13] = {IridescentFan},
	[keepsakeBaseID + 14] = {VividSea},
	[keepsakeBaseID + 15] = {BarleySheaf},
	[keepsakeBaseID + 16] = {HarmonicPhoton},
	[keepsakeBaseID + 17] = {BeautifulMirror},
	[keepsakeBaseID + 18] = {AdamantShard},
	[keepsakeBaseID + 19] = {EverlastingEmber},
	[keepsakeBaseID + 20] = {SwordHilt},
	[keepsakeBaseID + 21] = {GorgonAmulet},
	[keepsakeBaseID + 22] = {FigLeaf},
	[keepsakeBaseID + 23] = {SilkenSash},
	[keepsakeBaseID + 24] = {AromaticPhial},
	[keepsakeBaseID + 25] = {ConcaveStone},
	[keepsakeBaseID + 26] = {LionFang},
	[keepsakeBaseID + 27] = {BlackenedFleece},
	[keepsakeBaseID + 28] = {CrystalFigurine},
	[keepsakeBaseID + 29] = {ExperimentalHammer},
	[keepsakeBaseID + 30] = {JeweledPom},
	[keepsakeBaseID + 31] = {CallingCard},
	[keepsakeBaseID + 32] = {TimePiece},
	[keepsakeBaseID + 33] = {TranscendentEmbryo},
	-- weapons
	[weaponBaseID + 1] = {Descura},
	[weaponBaseID + 2] = {LimAndOros},
	[weaponBaseID + 3] = {Ygnium},
	[weaponBaseID + 4] = {Zorephet},
	[weaponBaseID + 5] = {Revaal},
	[weaponBaseID + 6] = {Xinth},
	-- tools
	[toolBaseID + 1] = {CrescentPick},
	[toolBaseID + 2] = {TabletOfPeace},
	[toolBaseID + 3] = {SilverSpade},
	[toolBaseID + 4] = {RodOfFishing},
}