Hecate:connect_one_way(Narcissus)
Hecate:connect_one_way(Hermes)
ScyllaBoss:connect_one_way(Echo)
Ephyra:connect_one_way(Medea)
Ephyra:connect_one_way(Heracles)
PolyphemusBoss:connect_one_way(Icarus)
PolyphemusBoss:connect_one_way(Circe)
Eris:connect_one_way(Eris)
Eris:connect_one_way(Dionysus)

Menu:connect_one_way(Moros, function() return Has(DoomedReckoning) end)

Menu:connect_one_way(GodKeepsakeRule(Zeus))
Menu:connect_one_way(GodKeepsakeRule(Hera))
Menu:connect_one_way(GodKeepsakeRule(Poseidon))
Menu:connect_one_way(GodKeepsakeRule(Demeter))
Menu:connect_one_way(GodKeepsakeRule(Apollo))
Menu:connect_one_way(GodKeepsakeRule(Aphrodite))
Menu:connect_one_way(GodKeepsakeRule(Hephaestus))
Menu:connect_one_way(GodKeepsakeRule(Hestia))
Menu:connect_one_way(GodKeepsakeRule(Ares))
Menu:connect_one_way(GodKeepsakeRule(Athena))
